name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Run Ruff linting
        run: |
          source .venv/bin/activate
          ruff check src/ --output-format=github

      - name: Run Ruff import sorting check
        run: |
          source .venv/bin/activate
          ruff check --select I src/ --output-format=github

      - name: Run Ruff format check
        run: |
          source .venv/bin/activate
          ruff format --check src/

      - name: Run mypy type checking
        run: |
          source .venv/bin/activate
          mypy src/ || true
        continue-on-error: true  # Don't fail the workflow on mypy errors initially

  summary:
    name: Code Quality Summary
    runs-on: ubuntu-latest
    needs: lint-and-format
    if: always()

    steps:
      - name: Check results
        run: |
          if [ "${{ needs.lint-and-format.result }}" == "failure" ]; then
            echo "❌ Code quality checks failed"
            exit 1
          else
            echo "✅ All code quality checks passed"
          fi
